#!/bin/sh
function cloud_install {
	echo "Downloading cloud";
	curl -O https://cloud.elkjop.no/update/elkjop/release/elkjop.dmg;
	echo "Mounting";
	hdiutil mount elkjop.dmg;
	echo "Installing";
	cp -R "/Volumes/Elkjøp Cloud/Jotta.app" /Applications;
	echo "Unmounting";
	hdiutil unmount "/Volumes/Elkjøp Cloud/";	
}
function libreoffice_install {
        echo "Downloading LibreOffice";
	LOVERSION=$(curl -s 'http://download.documentfoundation.org/libreoffice/stable/' | grep -o '<a .*href=.*>' | sed -e 's/<a /\<a /g' | sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' | egrep -o "([0-9]{1,}\.)+[0-9]{1,}" | sort -t. -k 1,1nr -k 2,2nr -k 3,3nr | sed -n '1p')
        echo $LOVERSION;
	#echo https://mirrors.dotsrc.org/tdf/libreoffice/stable/$LOVERSION/mac/x86_64/LibreOffice_"$LOVERSION"_MacOS_x86-64.dmg;
	curl -O https://mirrors.dotsrc.org/tdf/libreoffice/stable/$LOVERSION/mac/x86_64/LibreOffice_"$LOVERSION"_MacOS_x86-64.dmg;
        ls;
	echo "Mounting";
	hdiutil mount LibreOffice_"$LOVERSION"_MacOS_x86-64.dmg;
	echo "Installing";
	cp -R "/Volumes/LibreOffice/LibreOffice.app" /Applications;
	echo "Unmounting";
        hdiutil unmount "/Volumes/LibreOffice/";
}
function chrome_install {
        echo "Downloading Google Chrome";
        curl -O https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg;
        ls;
        echo "Mounting";
        hdiutil mount googlechrome.dmg;
        echo "Installing";
        cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications;
        echo "Unmounting";
        hdiutil unmount "/Volumes/Google Chrome/";
}
function ccleaner_install {
        echo "Downloading CCleaner";
	LOCCLEANER=$(curl -s 'www.ccleaner.com/ccleaner/download?mac' | grep -o '<a .*href=.*>' | sed -e 's/<a /\<a /g' | sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' | grep "CCMacSetup" | sed -n '1p');
        echo $LOCCLEANER;
	curl -O $LOCCLEANER;
	FILE=$(ls | grep "CCMacSetup");
        echo "Mounting";
        hdiutil mount $FILE;
        echo "Installing";
        cp -R "/Volumes/CCleaner/CCleaner.app" /Applications;
        echo "Unmounting";
        hdiutil unmount "/Volumes/CCleaner/";
}

function callingcard_install {
    echo "[InternetShortcut]" > remotefix.url
    echo "URL=https://www.elkjop.no/cms/20140218_092724/remotefix/" >> remotefix.url
    echo "IconIndex=0" >> remotefix.url
    echo "IconIndex=0" >> remotefix.url
    echo "Writing to desktop"
    cp remotefix.url "$HOME/Desktop/Elkjøp Remote Fix.url"
}

function kg {
    sudo echo ""
    libreoffice_install
    chrome_install
    ccleaner_install
    softupdate
}

function sa {
    kg
    callingcard_install
    cloud_install
}
function softupdate {
	echo "--------------------------------------------"
	echo "Searching and installing recommended updates"
	echo "--------------------------------------------"
	sudo softwareupdate -ir

}

LOCALVERSION=$(cat rtg);
EXTERNALVERSION=$(curl -s 'https://raw.githubusercontent.com/stemnic/Macintosh-Klargjoring/master/rtg')
clear
#echo "Current temp:$TMPDIR"
cd $TMPDIR
rm -Rf RTG
mkdir RTG
cd RTG
echo "Macintosh Klargjøring"
echo "Ole Sivert Aarhaug 2017"
echo "--------------------"
if [ "$LOCALVERSION" = "$EXTERNALVERSION" ]; then
    echo "You are running the latest version!"
else
    echo "NOT LATEST VERSION!"
    echo "Download new versions of Macintosh Klargjøring at:"
    echo "https://github.com/stemnic/Macintosh-Klargjoring"
fi;
echo "--------------------"
echo "Individual Applications"
echo "Latest Versions"
echo "--------------------"
echo "0. RemoteFix Install"
echo "1. Elkjop Cloud Install"
echo "2. Liber Office"
echo "3. Google Chrome"
echo "4. Ccleaner"
echo "5. (SUDO) Install recommended updates"
echo "--------------------"
echo "--------------------"
echo "Complete install"
echo "--------------------"
echo "11. KG: Installs Liber Office, Chrome, CCleaner and recommended updates"
echo "22. SA: Runs KG with Elkjop Cloud and RemoteFix"
echo "--------------------"
printf "What do you wan't todo?  -> "
read OPTION
echo "You Chose Opition $OPTION"
if [ $OPTION -eq 0 ]; then
    callingcard_install
fi;
if [ $OPTION -eq 1 ]; then
    cloud_install;
fi;
if [ $OPTION -eq 2 ]; then
    libreoffice_install;
fi;
if [ $OPTION -eq 3 ]; then
    chrome_install;
fi;
if [ $OPTION -eq 4 ]; then
    ccleaner_install;
fi;
if [ $OPTION -eq 5 ]; then
    softupdate;
fi;
if [ $OPTION -eq 11 ]; then
    kg;
fi;
if [ $OPTION -eq 22 ]; then
    sa;
fi;
